[package]
name = "piskel2amethyst"
version = "0.1.0"
authors = ["Jane Lusby <jlusby42@gmail.com>"]

[dependencies]
serde = "1.0.80"
serde_json = "1.0.33"
serde_derive = "1.0.80"
ron = "0.4.0"
failure = "0.1.3"
